### ISSUE TITLE
How cam I make the Camera View to open faster?

### ISSUE THREAD

**Issue by confile** [tdginternet/TGCameraViewController#27] opened 2015-01-08 13:42 UTC
The answers here might help you:

http://stackoverflow.com/questions/27203643/how-cam-i-make-the-camera-view-to-open-faster

**Comment by Bruno-Furtado** [comment] 2015-01-09 00:16
@confile,
The slowness isn't caused by the camera itself.
The effects make it slow.

Some changes [in this code point](https://github.com/tdginternet/TGCameraViewController/blob/2.0.1/TGCameraViewController/Control/TGCameraViewController.m#L90) can improve speed.

You think you could help us in this task?

**Comment by confile** [comment] 2015-01-09 12:57
I would like to help you but my iOS skills are still at the beginning. I might not be a great help yet.

**Comment by Bruno-Furtado** [comment] 2015-01-09 13:03
Once we have time we will improve this functionality, ok?
I can close this issue?

**Comment by confile** [comment] 2015-01-09 13:04
Great I love this App. Thank you for you great support.

**Comment by Bruno-Furtado** [comment] 2015-01-09 13:06
Thank you for help us so much!

**Closed by Bruno-Furtado** 2015-01-09 13:06 UTC
Labels: bug
