### ISSUE TITLE
Set tintColor for Camera button issue in ios 9

### ISSUE THREAD

**Issue by intersilindia** [tdginternet/TGCameraViewController#54] opened 2015-09-19 11:28 UTC
I just tested the code in ios 9 and found that the tint color which has been set to camera shot button doesnt appear 
It seems to be an ios 9 issue since the same code works on ios 8 and prior,not sure though but still I would like you to please help me figure out the exact reason

**Comment by miketraverso** [comment] 2015-09-21 14:25
I've had a user also report this on an iPhone 6+ on iOS9 but unfortunately I cannot reproduce this on an iPhone 6+ with iOS9

**Comment by philokezzar** [comment] 2015-09-22 08:30
I got the same issue in iP6 iOS 9

**Comment by miketraverso** [comment] 2015-09-22 17:03
So figured this out. The XIBs buttons have the TGTintButton class. As a result the image is never set. I'm planning to create a pull request later today with a fix where the code will explicitly set the correct images. Once that code is applied there is no longer an issue with missing image assets on the buttons. The reason flash always appears because that's explicitly being set within the code.

**Comment by woobione** [comment] 2015-09-23 08:43
I have the same issue. Looking forward to your pull @miketraverso :)

**Comment by miketraverso** [comment] 2015-09-24 18:29
BUG FIX: Update type to on return type.	e98b3cd
Added outlets and changed types of UIButton in code but TGTintedButto… …	88f6278
Added outlets and changed types of UIButton in code but TGTintedButto… …	 2652bd9

**Comment by ADSolutions** [comment] 2015-10-07 20:47
any news?

**Comment by miketraverso** [comment] 2015-10-07 21:13
I created the pull request a while back. Haven't seen any action on that and can't create my own branch. The links to my checkins are in the comment above though.

**Comment by ADSolutions** [comment] 2015-10-08 05:24
@miketraverso thank you! i'll try it now

**Comment by iHardikTrivedi** [comment] 2015-10-14 09:26
Thank you very much . . . 

It's work fine . . .

**Comment by 278swati** [comment] 2015-10-14 09:29
Thanks a ton... it helps a lot in my project as it won't works with device when i change color ... ur solution is really works as magic !

**Comment by alexandre-g** [comment] 2015-10-22 02:47
An easier fix would be just removing the `__weak` from these lines in TGTintedButton.m updateTintIfNeeded: method.
```
UIImage * __weak backgroundImage = [[self backgroundImageForState:UIControlStateNormal] imageWithRenderingMode:renderingMode];
[self setBackgroundImage:backgroundImage forState:UIControlStateNormal];
        
UIImage * __weak image = [[self imageForState:UIControlStateNormal] imageWithRenderingMode:renderingMode];
[self setImage:image forState:UIControlStateNormal];
```

Anyone here know if that will lead to leaked UIImages?

**Comment by MattiaConfalonieri** [comment] 2016-03-01 10:59
@alexandre-g are you sure your easy fix work?

**Comment by alexandre-g** [comment] 2016-03-01 11:15
@MattiaConfalonieri works very well, in 2 production apps

**Comment by abbasmousavi** [comment] 2016-03-01 12:32
It works in my production app too.

**Comment by macecchi** [comment] 2017-01-10 16:39
Fixed in #78 and released in v2.2.7.

**Closed by macecchi** 2017-01-10 16:39 UTC
